/**
 * Interactive HTML report fixture (generated by TestWriteReportE2EFixture).
 */
import { expect, test } from '@playwright/test'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const reportPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../fixtures/report/sample.html')
const reportURL = 'file:///' + reportPath.replace(/\\/g, '/')

test.describe('HTML report viewer', () => {
  test('auto-selects failed scenario and step', async ({ page }) => {
    await page.goto(reportURL)
    await expect(page.locator('.step-node.failed.active')).toBeVisible({ timeout: 10_000 })
    await expect(page.locator('#inspector')).toContainText('Шаг #2')
  })

  test('action log tab syncs with step selection', async ({ page }) => {
    await page.goto(reportURL)
    await page.locator('#tab-actionlog').click()
    await expect(page.locator('#actionlog tr.failed.active')).toBeVisible()
    await page.locator('#actionlog tr[data-idx="0"]').click()
    await expect(page.locator('#inspector')).toContainText('Шаг #1')
    await page.locator('#tab-timeline').click()
    await expect(page.locator('.step-node.active')).toHaveAttribute('data-idx', '0')
  })

  test('failed-only filter hides passed scenarios', async ({ page }) => {
    await page.goto(reportURL)
    await page.locator('#filter-failed').check()
    await expect(page.locator('.scenario-item')).toHaveCount(1)
  })

  test('inspector shows page context and CI compare', async ({ page }) => {
    await page.goto(reportURL)
    await expect(page.locator('#ci-compare')).toContainText('CI')
    await expect(page.locator('#inspector')).toContainText('Example')
    await expect(page.locator('#inspector')).toContainText('trace')
  })

  test('run diff table shows step status across runs', async ({ page }) => {
    await page.goto(reportURL)
    await expect(page.locator('.run-diff td.diff-failed').first()).toBeVisible()
    await expect(page.locator('.step-node .spark-bar').first()).toBeVisible()
  })

  test('trace mini-viewer tab syncs with steps', async ({ page }) => {
    await page.goto(reportURL)
    await expect(page.locator('#tab-trace')).toBeVisible()
    await page.locator('#tab-trace').click()
    await expect(page.locator('#traceview .trace-event-row').first()).toBeVisible()
    await page.locator('#traceview .trace-step-row[data-idx="0"]').click()
    await expect(page.locator('.step-node.active')).toHaveAttribute('data-idx', '0')
  })

  test('offline trace zip import populates trace tab', async ({ page }) => {
    const traceZip = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../fixtures/report/sample-trace.zip')
    await page.goto(reportURL)
    page.once('dialog', (d) => d.accept())
    const zipBytes = await import('node:fs').then((fs) => fs.promises.readFile(traceZip))
    await page.locator('#trace-drop').evaluate((el, payload) => {
      const dt = new DataTransfer()
      const file = new File([new Uint8Array(payload.bytes)], payload.name, { type: 'application/zip' })
      dt.items.add(file)
      el.dispatchEvent(new DragEvent('drop', { bubbles: true, dataTransfer: dt }))
    }, { bytes: [...zipBytes], name: 'sample-trace.zip' })
    await page.locator('#tab-trace').click()
    await expect(page.locator('#traceview .trace-event-row')).toHaveCount(2)
    await expect(page.locator('#traceview .trace-event-row').first()).toContainText('goto')
  })

  test('example feature report opens failed step', async ({ page }) => {
    const examplePath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../fixtures/report/example-report.html')
    const url = 'file:///' + examplePath.replace(/\\/g, '/')
    await page.goto(url)
    await expect(page.locator('.step-node.failed.active')).toBeVisible({ timeout: 10_000 })
    await expect(page.locator('#inspector')).toContainText('Example Domain')
    await expect(page.locator('#inspector')).toContainText('text mismatch')
  })
})
