package allure

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/bafgion/scenaria-golang/internal/player"
	"github.com/google/uuid"
)

const markerFile = ".scenaria-allure-results"

type resultFile struct {
	UUID          string         `json:"uuid"`
	HistoryID     string         `json:"historyId,omitempty"`
	Name          string         `json:"name"`
	FullName      string         `json:"fullName,omitempty"`
	Status        string         `json:"status"`
	StatusDetails *statusDetails `json:"statusDetails,omitempty"`
	Stage         string         `json:"stage"`
	Start         int64          `json:"start"`
	Stop          int64          `json:"stop"`
	Labels        []label        `json:"labels,omitempty"`
	Attachments   []attachment   `json:"attachments,omitempty"`
}

type attachment struct {
	Name   string `json:"name"`
	Source string `json:"source"`
	Type   string `json:"type"`
}

type statusDetails struct {
	Message string `json:"message,omitempty"`
	Trace   string `json:"trace,omitempty"`
}

type label struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// WriteResults writes Allure 2 *-result.json files for each scenario.
func WriteResults(dir string, result player.ExecutionResult) error {
	if strings.TrimSpace(dir) == "" {
		return fmt.Errorf("allure output directory is required")
	}
	dir = filepath.Clean(dir)
	ok, err := canCleanAllureDir(dir)
	if err != nil {
		return fmt.Errorf("check allure dir: %w", err)
	}
	if !ok {
		return fmt.Errorf("refusing to replace unmarked allure directory %q (expected %s marker or empty directory)", dir, markerFile)
	}
	staging, err := os.MkdirTemp(filepath.Dir(dir), filepath.Base(dir)+".staging-*")
	if err != nil {
		return fmt.Errorf("create allure staging dir: %w", err)
	}
	defer func() { _ = os.RemoveAll(staging) }()
	if err := writeMarker(staging); err != nil {
		return err
	}

	base := time.Now().UnixMilli()
	for i, scenario := range result.ScenarioResults {
		start := base + int64(i*100)
		stop := start + 50
		if stop <= start {
			stop = start + 1
		}
		if err := writeScenarioResult(staging, scenario, start, stop); err != nil {
			return err
		}
	}
	if err := os.RemoveAll(dir); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("replace allure dir: %w", err)
	}
	if err := os.Rename(staging, dir); err != nil {
		return fmt.Errorf("activate allure staging dir: %w", err)
	}
	return nil
}

func cleanAllureDir(dir string) error {
	if ok, err := canCleanAllureDir(dir); err != nil || !ok {
		if err != nil {
			return err
		}
		return fmt.Errorf("refusing to clean unmarked allure directory %q (expected %s marker or empty directory)", dir, markerFile)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	for _, entry := range entries {
		name := entry.Name()
		if name == markerFile {
			continue
		}
		if strings.HasSuffix(name, "-result.json") || strings.Contains(name, "-attachment") {
			if err := os.Remove(filepath.Join(dir, name)); err != nil && !os.IsNotExist(err) {
				return err
			}
		}
	}
	return nil
}

func canCleanAllureDir(dir string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return true, nil
		}
		return false, err
	}
	if len(entries) == 0 {
		return true, nil
	}
	for _, entry := range entries {
		if entry.Name() == markerFile {
			return true, nil
		}
	}
	return false, nil
}

func writeMarker(dir string) error {
	path := filepath.Join(dir, markerFile)
	payload := []byte("generated by scenaria\n")
	if err := writeAtomicFile(path, payload); err != nil {
		return fmt.Errorf("write allure marker: %w", err)
	}
	return nil
}

func writeScenarioResult(dir string, scenario player.ScenarioResult, start, stop int64) error {
	status := mapStatus(scenario.Status)
	id := uuid.New().String()
	entry := resultFile{
		UUID:      id,
		HistoryID: historyID(scenario),
		Name:      scenario.Scenario,
		FullName:  scenario.FeaturePath + "::" + scenario.Scenario,
		Status:    status,
		Stage:     "finished",
		Start:     start,
		Stop:      stop,
		Labels: []label{
			{Name: "suite", Value: filepath.Base(scenario.FeaturePath)},
			{Name: "parentSuite", Value: scenario.FeaturePath},
			{Name: "framework", Value: "scenaria"},
			{Name: "language", Value: "go"},
		},
	}
	if scenario.Message != "" && status != "passed" {
		entry.StatusDetails = &statusDetails{Message: scenario.Message}
	}
	if status != "passed" {
		var err error
		entry.Attachments, err = writeFailureAttachments(dir, entry.Attachments, scenario)
		if err != nil {
			return err
		}
	}
	payload, err := json.Marshal(entry)
	if err != nil {
		return fmt.Errorf("encode allure result: %w", err)
	}
	path := filepath.Join(dir, id+"-result.json")
	if err := writeAtomicFile(path, payload); err != nil {
		return fmt.Errorf("write allure result %q: %w", path, err)
	}
	return nil
}

func mapStatus(status string) string {
	switch strings.ToLower(strings.TrimSpace(status)) {
	case "passed", "pass", "ok":
		return "passed"
	case "canceled", "cancelled":
		return "skipped"
	case "skipped", "skip", "dry-run":
		return "skipped"
	case "broken":
		return "broken"
	default:
		return "failed"
	}
}

func historyID(scenario player.ScenarioResult) string {
	key := scenario.CaseID
	if strings.TrimSpace(key) == "" {
		key = scenario.FeaturePath + "::" + scenario.Scenario
	}
	return uuid.NewSHA1(uuid.NameSpaceURL, []byte(key)).String()
}

func writeFailureAttachments(dir string, existing []attachment, scenario player.ScenarioResult) ([]attachment, error) {
	out := existing
	screenshot := scenario.ScreenshotPNG
	if len(screenshot) == 0 && strings.TrimSpace(scenario.ScreenshotPath) != "" {
		if b, err := os.ReadFile(scenario.ScreenshotPath); err == nil {
			screenshot = b
		}
	}
	if len(screenshot) > 0 {
		item, err := saveAttachment(dir, "screenshot", ".png", "image/png", screenshot)
		if err != nil {
			return nil, err
		}
		out = append(out, item)
	}
	trace := scenario.TraceZIP
	if len(trace) == 0 && strings.TrimSpace(scenario.TraceZIPPath) != "" {
		if b, err := os.ReadFile(scenario.TraceZIPPath); err == nil {
			trace = b
		}
	}
	if len(trace) > 0 {
		item, err := saveAttachment(dir, "trace", ".zip", "application/zip", trace)
		if err != nil {
			return nil, err
		}
		out = append(out, item)
	}
	video := scenario.VideoWebM
	if len(video) == 0 && strings.TrimSpace(scenario.VideoWebMPath) != "" {
		if b, err := os.ReadFile(scenario.VideoWebMPath); err == nil {
			video = b
		}
	}
	if len(video) > 0 {
		item, err := saveAttachment(dir, "video", ".webm", "video/webm", video)
		if err != nil {
			return nil, err
		}
		out = append(out, item)
	}
	return out, nil
}

func saveAttachment(dir, name, ext, mime string, payload []byte) (attachment, error) {
	attachID := uuid.New().String()
	source := attachID + "-attachment" + ext
	if err := writeAtomicFile(filepath.Join(dir, source), payload); err != nil {
		return attachment{}, fmt.Errorf("write allure attachment: %w", err)
	}
	return attachment{Name: name, Source: source, Type: mime}, nil
}

func writeAtomicFile(path string, payload []byte) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".allure-write-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	if _, err := tmp.Write(payload); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return err
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return err
	}
	return nil
}
