// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArtifactExists(arg1) {
  return window['go']['wailsapp']['App']['ArtifactExists'](arg1);
}

export function BundledExamplesPath() {
  return window['go']['wailsapp']['App']['BundledExamplesPath']();
}

export function CancelOTP() {
  return window['go']['wailsapp']['App']['CancelOTP']();
}

export function CancelRecording() {
  return window['go']['wailsapp']['App']['CancelRecording']();
}

export function DeleteFeature(arg1) {
  return window['go']['wailsapp']['App']['DeleteFeature'](arg1);
}

export function DuplicateFeature(arg1) {
  return window['go']['wailsapp']['App']['DuplicateFeature'](arg1);
}

export function ImportFeatures(arg1, arg2) {
  return window['go']['wailsapp']['App']['ImportFeatures'](arg1, arg2);
}

export function MoveFeature(arg1, arg2) {
  return window['go']['wailsapp']['App']['MoveFeature'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['wailsapp']['App']['CheckUpdate']();
}

export function Export(arg1) {
  return window['go']['wailsapp']['App']['Export'](arg1);
}

export function FocusBrowser() {
  return window['go']['wailsapp']['App']['FocusBrowser']();
}

export function HighlightFeature(arg1) {
  return window['go']['wailsapp']['App']['HighlightFeature'](arg1);
}

export function HTTPAuthForHost(arg1) {
  return window['go']['wailsapp']['App']['HTTPAuthForHost'](arg1);
}

export function ImportJSON(arg1) {
  return window['go']['wailsapp']['App']['ImportJSON'](arg1);
}

export function InitProject() {
  return window['go']['wailsapp']['App']['InitProject']();
}

export function IsRecordingPaused() {
  return window['go']['wailsapp']['App']['IsRecordingPaused']();
}

export function ListRunResults(arg1) {
  return window['go']['wailsapp']['App']['ListRunResults'](arg1);
}

export function ListHTTPAuthHosts() {
  return window['go']['wailsapp']['App']['ListHTTPAuthHosts']();
}

export function ListTestClients() {
  return window['go']['wailsapp']['App']['ListTestClients']();
}

export function LoadRecents() {
  return window['go']['wailsapp']['App']['LoadRecents']();
}

export function LoadSettings() {
  return window['go']['wailsapp']['App']['LoadSettings']();
}

export function OpenFolder(arg1) {
  return window['go']['wailsapp']['App']['OpenFolder'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['wailsapp']['App']['OpenProject'](arg1);
}

export function ParseEditorSteps(arg1) {
  return window['go']['wailsapp']['App']['ParseEditorSteps'](arg1);
}

export function PauseRecording() {
  return window['go']['wailsapp']['App']['PauseRecording']();
}

export function PickOpenFile(arg1) {
  return window['go']['wailsapp']['App']['PickOpenFile'](arg1);
}

export function PickProjectFolder() {
  return window['go']['wailsapp']['App']['PickProjectFolder']();
}

export function PickSaveFile(arg1, arg2) {
  return window['go']['wailsapp']['App']['PickSaveFile'](arg1, arg2);
}

export function PickSelector() {
  return window['go']['wailsapp']['App']['PickSelector']();
}

export function PickerStepChoices(arg1, arg2) {
  return window['go']['wailsapp']['App']['PickerStepChoices'](arg1, arg2);
}

export function ProjectArtifacts() {
  return window['go']['wailsapp']['App']['ProjectArtifacts']();
}

export function ProjectPath() {
  return window['go']['wailsapp']['App']['ProjectPath']();
}

export function ReadFeature(arg1) {
  return window['go']['wailsapp']['App']['ReadFeature'](arg1);
}

export function RefactorCollapseBlankLines(arg1) {
  return window['go']['wailsapp']['App']['RefactorCollapseBlankLines'](arg1);
}

export function RefactorNormalizeIndents(arg1) {
  return window['go']['wailsapp']['App']['RefactorNormalizeIndents'](arg1);
}

export function RefactorReplaceInText(arg1, arg2, arg3, arg4) {
  return window['go']['wailsapp']['App']['RefactorReplaceInText'](arg1, arg2, arg3, arg4);
}

export function RefactorUpdateStartURLs(arg1, arg2) {
  return window['go']['wailsapp']['App']['RefactorUpdateStartURLs'](arg1, arg2);
}

export function RememberRecentFeature(arg1) {
  return window['go']['wailsapp']['App']['RememberRecentFeature'](arg1);
}

export function ReplaceInProject(arg1) {
  return window['go']['wailsapp']['App']['ReplaceInProject'](arg1);
}

export function RememberRecentProject(arg1) {
  return window['go']['wailsapp']['App']['RememberRecentProject'](arg1);
}

export function RemoveHTTPAuth(arg1) {
  return window['go']['wailsapp']['App']['RemoveHTTPAuth'](arg1);
}

export function ResumeRecording() {
  return window['go']['wailsapp']['App']['ResumeRecording']();
}

export function Run(arg1) {
  return window['go']['wailsapp']['App']['Run'](arg1);
}

export function RunVanessa(arg1) {
  return window['go']['wailsapp']['App']['RunVanessa'](arg1);
}

export function SaveFeature(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveFeature'](arg1, arg2);
}

export function SaveHTTPAuth(arg1) {
  return window['go']['wailsapp']['App']['SaveHTTPAuth'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['wailsapp']['App']['SaveSettings'](arg1);
}

export function SearchSteps(arg1) {
  return window['go']['wailsapp']['App']['SearchSteps'](arg1);
}

export function StartRecord(arg1) {
  return window['go']['wailsapp']['App']['StartRecord'](arg1);
}

export function SubmitOTPCode(arg1) {
  return window['go']['wailsapp']['App']['SubmitOTPCode'](arg1);
}

export function TestClientDetails(arg1) {
  return window['go']['wailsapp']['App']['TestClientDetails'](arg1);
}

export function UndoRecordedStep() {
  return window['go']['wailsapp']['App']['UndoRecordedStep']();
}

export function Validate(arg1, arg2) {
  return window['go']['wailsapp']['App']['Validate'](arg1, arg2);
}

export function ValidateFeature(arg1) {
  return window['go']['wailsapp']['App']['ValidateFeature'](arg1);
}

export function Version() {
  return window['go']['wailsapp']['App']['Version']();
}
