// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function AnalyzeScenarioHints(arg1:string):Promise<Array<gui.ScenarioHintDTO>>;

export function ApplyScenarioHintFix(arg1:gui.ScenarioHintFixRequest):Promise<gui.RefactorResult>;

export function ArtifactExists(arg1:string):Promise<boolean>;

export function BundledExamplesPath():Promise<string>;

export function CancelOTP():Promise<void>;

export function CancelRecording():Promise<void>;

export function CheckUpdate():Promise<gui.RunResult>;

export function DeleteFeature(arg1:string):Promise<void>;

export function DuplicateFeature(arg1:string):Promise<string>;

export function ImportFeatures(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function MoveFeature(arg1:string,arg2:string):Promise<string>;

export function Export(arg1:gui.ExportRequest):Promise<gui.RunResult>;

export function FocusBrowser():Promise<void>;

export function HighlightFeature(arg1:string):Promise<Array<gui.HighlightSpan>>;

export function HTTPAuthForHost(arg1:string):Promise<gui.HTTPAuthCredentials>;

export function ImportJSON(arg1:gui.ImportRequest):Promise<gui.RunResult>;

export function InitProject():Promise<string>;

export function IsRecordingPaused():Promise<boolean>;

export function ListRunResults(arg1:number):Promise<Array<gui.RunResultEntry>>;

export function ListHTTPAuthHosts():Promise<Array<string>>;

export function ListTestClients():Promise<Array<string>>;

export function LoadRecents():Promise<gui.RecentsDTO>;

export function LoadSettings():Promise<gui.AppSettingsDTO>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenProject(arg1:string):Promise<gui.ProjectInfo>;

export function ParseEditorSteps(arg1:string):Promise<Array<gui.EditorStepRow>>;

export function PauseRecording():Promise<void>;

export function PickOpenFile(arg1:string):Promise<string>;

export function PickProjectFolder():Promise<string>;

export function PickSaveFile(arg1:string,arg2:string):Promise<string>;

export function PickSelector():Promise<gui.PickSelectorResult>;

export function PickerStepChoices(arg1:string,arg2:string):Promise<Array<gui.PickerStepChoice>>;

export function ProjectArtifacts():Promise<gui.ProjectArtifacts>;

export function ProjectPath():Promise<string>;

export function ReadFeature(arg1:string):Promise<string>;

export function RefactorCollapseBlankLines(arg1:string):Promise<string>;

export function RefactorNormalizeIndents(arg1:string):Promise<string>;

export function RefactorUpdateStartURLs(arg1:string,arg2:string):Promise<gui.RefactorResult>;

export function RefactorReplaceInText(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<gui.RefactorResult>;

export function ReplaceInProject(arg1:gui.ProjectReplaceRequest):Promise<gui.ProjectReplaceResult>;

export function RememberRecentFeature(arg1:string):Promise<void>;

export function RememberRecentProject(arg1:string):Promise<void>;

export function RemoveHTTPAuth(arg1:string):Promise<void>;

export function ResumeRecording():Promise<void>;

export function Run(arg1:gui.RunRequest):Promise<gui.RunResult>;

export function RunVanessa(arg1:boolean):Promise<gui.RunResult>;

export function SaveFeature(arg1:string,arg2:string):Promise<void>;

export function SaveHTTPAuth(arg1:gui.HTTPAuthRequest):Promise<void>;

export function SaveSettings(arg1:gui.AppSettingsDTO):Promise<void>;

export function SearchSteps(arg1:string):Promise<Array<gui.StepCatalogEntry>>;

export function StartRecord(arg1:gui.RecordRequest):Promise<void>;

export function SubmitOTPCode(arg1:string):Promise<void>;

export function TestClientDetails(arg1:string):Promise<string>;

export function UndoRecordedStep():Promise<boolean>;

export function Validate(arg1:string,arg2:boolean):Promise<gui.RunResult>;

export function ValidateFeature(arg1:string):Promise<Array<gui.ValidationIssue>>;

export function Version():Promise<string>;
