// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitProject() {
  return window['go']['wailsapp']['App']['InitProject']();
}

export function ListTestClients() {
  return window['go']['wailsapp']['App']['ListTestClients']();
}

export function LoadSettings() {
  return window['go']['wailsapp']['App']['LoadSettings']();
}

export function OpenProject(arg1) {
  return window['go']['wailsapp']['App']['OpenProject'](arg1);
}

export function PickProjectFolder() {
  return window['go']['wailsapp']['App']['PickProjectFolder']();
}

export function ProjectPath() {
  return window['go']['wailsapp']['App']['ProjectPath']();
}

export function ReadFeature(arg1) {
  return window['go']['wailsapp']['App']['ReadFeature'](arg1);
}

export function Run(arg1) {
  return window['go']['wailsapp']['App']['Run'](arg1);
}

export function SaveFeature(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveFeature'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['wailsapp']['App']['SaveSettings'](arg1);
}

export function SearchSteps(arg1) {
  return window['go']['wailsapp']['App']['SearchSteps'](arg1);
}

export function TestClientDetails(arg1) {
  return window['go']['wailsapp']['App']['TestClientDetails'](arg1);
}

export function Validate(arg1, arg2) {
  return window['go']['wailsapp']['App']['Validate'](arg1, arg2);
}

export function Version() {
  return window['go']['wailsapp']['App']['Version']();
}
