// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOTP() {
  return window['go']['wailsapp']['App']['CancelOTP']();
}

export function CancelRecording() {
  return window['go']['wailsapp']['App']['CancelRecording']();
}

export function Export(arg1) {
  return window['go']['wailsapp']['App']['Export'](arg1);
}

export function ImportJSON(arg1) {
  return window['go']['wailsapp']['App']['ImportJSON'](arg1);
}

export function InitProject() {
  return window['go']['wailsapp']['App']['InitProject']();
}

export function IsRecordingPaused() {
  return window['go']['wailsapp']['App']['IsRecordingPaused']();
}

export function ListTestClients() {
  return window['go']['wailsapp']['App']['ListTestClients']();
}

export function LoadSettings() {
  return window['go']['wailsapp']['App']['LoadSettings']();
}

export function OpenFolder(arg1) {
  return window['go']['wailsapp']['App']['OpenFolder'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['wailsapp']['App']['OpenProject'](arg1);
}

export function PauseRecording() {
  return window['go']['wailsapp']['App']['PauseRecording']();
}

export function PickOpenFile(arg1) {
  return window['go']['wailsapp']['App']['PickOpenFile'](arg1);
}

export function PickProjectFolder() {
  return window['go']['wailsapp']['App']['PickProjectFolder']();
}

export function PickSaveFile(arg1, arg2) {
  return window['go']['wailsapp']['App']['PickSaveFile'](arg1, arg2);
}

export function ProjectPath() {
  return window['go']['wailsapp']['App']['ProjectPath']();
}

export function ReadFeature(arg1) {
  return window['go']['wailsapp']['App']['ReadFeature'](arg1);
}

export function ResumeRecording() {
  return window['go']['wailsapp']['App']['ResumeRecording']();
}

export function Run(arg1) {
  return window['go']['wailsapp']['App']['Run'](arg1);
}

export function RunVanessa(arg1) {
  return window['go']['wailsapp']['App']['RunVanessa'](arg1);
}

export function SaveFeature(arg1, arg2) {
  return window['go']['wailsapp']['App']['SaveFeature'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['wailsapp']['App']['SaveSettings'](arg1);
}

export function SearchSteps(arg1) {
  return window['go']['wailsapp']['App']['SearchSteps'](arg1);
}

export function StartRecord(arg1) {
  return window['go']['wailsapp']['App']['StartRecord'](arg1);
}

export function SubmitOTPCode(arg1) {
  return window['go']['wailsapp']['App']['SubmitOTPCode'](arg1);
}

export function TestClientDetails(arg1) {
  return window['go']['wailsapp']['App']['TestClientDetails'](arg1);
}

export function Validate(arg1, arg2) {
  return window['go']['wailsapp']['App']['Validate'](arg1, arg2);
}

export function ValidateFeature(arg1) {
  return window['go']['wailsapp']['App']['ValidateFeature'](arg1);
}

export function Version() {
  return window['go']['wailsapp']['App']['Version']();
}
