// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function InitProject():Promise<string>;

export function ListTestClients():Promise<Array<string>>;

export function LoadSettings():Promise<gui.AppSettingsDTO>;

export function OpenProject(arg1:string):Promise<gui.ProjectInfo>;

export function PickProjectFolder():Promise<string>;

export function ProjectPath():Promise<string>;

export function ReadFeature(arg1:string):Promise<string>;

export function Run(arg1:gui.RunRequest):Promise<gui.RunResult>;

export function SaveFeature(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:gui.AppSettingsDTO):Promise<void>;

export function SearchSteps(arg1:string):Promise<Array<gui.StepCatalogEntry>>;

export function TestClientDetails(arg1:string):Promise<string>;

export function Validate(arg1:string,arg2:boolean):Promise<gui.RunResult>;

export function Version():Promise<string>;
